### ISSUE TITLE
Using both origin and destination locations 

### ISSUE THREAD

**Issue by lydiakayh** [kosukeimai/wru#103]
Hello! I am wondering if there is a way to incorporate both the origin and destination locations for those who move from one year to the next when imputing race rather than using just one geolocation. I can work around this by predicting race using origin location and destination location and then averaging their predictions, but this doesn't seem like the best way.

**Comment by kosukeimai** [comment]
That's an interesting question but we don't currently have data or methods to incorporate such information.
