### ISSUE TITLE
WRU 2.0 Sex and Age

### ISSUE THREAD

**Issue by ameier88** [kosukeimai/wru#108]
Hello, 

With the new update, is sex, age, and party now available using the 2020 census data for the predict_race function? 
Also, I'm seeing that version 2.0.0 was released last month but I'm not seeing the update in R or on CRAN. Is there a release date? 

Thank you!

**Comment by 1beb** [comment]
@carlson9 

This one will require some finagling with the census API. Let's talk about it.

**Comment by 1beb** [comment]
This is being released with 3.0.0 as part of #120
