### ISSUE TITLE
object 'State.FIPS' not found

### ISSUE THREAD

**Issue by davidmcclendon** [kosukeimai/wru#110]
I'm having an issue with the latest 2.0 update. When I try to pull the latest census data with `get_census_data`, I get this error: `Error in get("State.FIPS") : object 'State.FIPS' not found`

It happens with the latest developer and CRAN versions.

Here's the code I'm running
`get_census_data( key = Sys.getenv("CENSUS_API_KEY"), states = c("NJ", "NY"), age = FALSE, sex = FALSE)`

Thanks in advance!

**Comment by 1beb** [comment]
This PR should fix that issue. Can you let me know what version of the software you are using? 
https://github.com/kosukeimai/wru/pull/107
