### ISSUE TITLE
standardize case (v. minor point)

### ISSUE THREAD

**Issue by soodoku** [kosukeimai/wru#12]
Function names have different kinds of cases:
https://github.com/kosukeimai/wru/tree/master/R

1. CamelCase for getCensusApi.R and vecToChunk.R
https://en.wikipedia.org/wiki/Camel_case

2. periods used to separate for name.clean.R, race.pred.R, census.helper.api.R

Hadley etc. strongly prefer snake case. See also this by Gelman:
http://andrewgelman.com/2012/08/28/migrating-from-dot-to-underscore/

My rec. would be to standardize case.

**Comment by kosukeimai** [comment]
A good point.  @kkprinceton Let's use underscores.

**Comment by kkprinceton** [comment]
Done.
