### ISSUE TITLE
Error in fBISG when using 'place'

### ISSUE THREAD

**Issue by DianaDaInLee** [kosukeimai/wru#129]
My dataset includes place FIPS along with full names, and I'm trying to use fBISG to generate predictions as follows:
```
df <- data.frame(place = '01000', state = 'NY', first = 'richard', surname = 'smith')
predict_race(voter.file = df,
             names.to.use = 'surname, first',
             census.geo = 'place', 
             census.key = '...', 
             model = 'fBISG',
             surname.only = FALSE,
             impute.missing = TRUE)
```
But it results in the following error which mentions 'county', which shouldn't be relevant if you're using place fips?
```
Error in split.default(voter.file$county, voter.file$state) : 
  first argument must be a vector
```

**Comment by 1beb** [comment]
Hi Diana, I will take a look at this after the next release goes through. Does your voter file not include state and county?

**Comment by DianaDaInLee** [comment]
Thank you --- it includes state and place fips, but not county. Interestingly, the function works when I generate an empty county field: `df$county <- ""`.

**Comment by 1beb** [comment]
I'm going to close this one. It sounds like you may have created a custom census data object and missed out on some requirements that the software expects. If you feel like this isn't the case, let me know.
