### ISSUE TITLE
better error handling, arg. conflicts with sample data named voters 

### ISSUE THREAD

**Issue by soodoku** [kosukeimai/wru#13]
If I type in:

```
race.pred(voters)
```

I get:

```
Error in `[.data.frame`(voters, paste("r", eth[k], sep = "_")) : 
  undefined columns selected
```

Three fixes:
1. It may be good to provide better error handling if input not in desired format
2. Since there is data included in package called 'voters', may be a good idea to call the argument something else as lots of people will try to create a variable with the name voters, overwriting the sample db, which is just fine, but something that can also be easily avoided
3. voters also suggests that people must be voters. they don't have to be. they just have to plausibly registered citizens.

**Comment by kkprinceton** [comment]
We are working on improving the error handling and have made several changes that I will commit soon on the update-surname-handling branch. We are changing the name of the 'voters' object to 'voter.file' for now. Strictly speaking, the observations do not have to be voters, registered citizens, or any other type of person. As long as they have a name, the function can estimate their race.
