### ISSUE TITLE
Offline WRU

### ISSUE THREAD

**Issue by lhall8** [kosukeimai/wru#130]
I'm looking to use WRU to predict race in a data environment where I am unable to access the internet. Is there an expedited way to use uploaded census data, other than rewriting the package? I have already tried uploading my own Census data, however, within a Redivis environment, I cannot upload a list in RDS form but only CSV data frames. 

I am thinking that I will need to take the base code of WRU and alter it to accept a manipulated form of census data which I am able to upload. 

I am happy to discuss in further detail if needed, however, I appreciate any and all help!

**Comment by 1beb** [comment]
You can download the name data and census data in advance. Then it's just a matter of moving the files into the working directory and running your code by loading the census data as an argument. The code the downloads the name data will not download again if it sees the files in the directory. THere was a similar question. You'll also need to set: 

```
options("wru_data_wd" = TRUE)
```

This tells wru to look in the working directory for the name data.
