### ISSUE TITLE
Error in gzfile(file, "rb") : cannot open the connection

### ISSUE THREAD

**Issue by dkallattil** [kosukeimai/wru#143]
Some info on my specs: 
I am running macOS 13.0.1 (22A400), RStudio version 4.3.2, and wru 3.0.0. I was able to successfully run predict_race() with an older version of R 

This is the error I am getting: 

There was an error retrieving data: incorrect number of dimensions
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/var/folders/h8/p4qmr1s15cz6ry_vkcx1nz1r0000gp/T//RtmprezHYz/wru-data-first_c.rds', probable reason 'No such file or directory'

I've tried updating and downgrading my package version, and I have not been able to run predict_race() any time recently, so I don't think it's a connection issue. Any ideas for how to resolve this?

**Comment by 1beb** [comment]
Please update to the newest version of wru (3.0.1 is on CRAN). Thanks!
