### ISSUE TITLE
error when installing old version from source

### ISSUE THREAD

**Issue by liaoaoyuan97** [kosukeimai/wru#144]
Hi,

I’ve used an old version(1.0.1), as it allows an argument for the function: `wru::predict_race()`: `surname.year` to specify the year of the census surname statistics for my project.  My project includes historical data, so I want to make sure the imputed race at its best aligned with the naming trends at different times. The old version used to work fine until a point I see this error message:

> There was an error retrieving dataincorrect number of dimensions
> Error in gzfile(file, "rb") : cannot open the connection
> In addition: Warning message:
> In gzfile(file, "rb") :
>   cannot open compressed file '/var/folders/zb/d8phfv110gv94fcv_k4dlnfw0000gn/T//RtmpkYudFP/wru-data-first_c.rds', probable reason 'No such file or directory'

I know [the issue](https://github.com/kosukeimai/wru/issues/143) can be fixed by updating the version, but I don’t think the newest version allows users to control the year of the census surname statistics anymore. At least, I cannot find it in the [documentation](https://cran.r-project.org/web/packages/wru/wru.pdf). I tried to download the old version from [CRAN](https://cran.r-project.org/src/contrib/Archive/wru/) but came across the above error msg. The installation command I used is: `install.packages('C:/Users/User/Downloads/wru_1.0.1.tar.gz', repos=NULL, type='source')`. 

My spec info:
Apple M2 chip(ARM64), MacOS 14.3, R:4.2.2 

Thanks!

**Comment by 1beb** [comment]
What year are you attempting to replicate?

**Comment by 1beb** [comment]
What year are you attempting to replicate?

**Comment by liaoaoyuan97** [comment]
> What year are you attempting to replicate?

You mean `surname.year`? It is 2000. The exact code is:

```
race_fbisg_2000 <- predict_race(voter.file = df_2000,
                                census.geo = "tract",
                                year = "2010",# geo data year, only 2010 or 2020 available 
                                surname.year = "2000",
                                names.to.use = "surname", #default
                                model = "fBISG")
```
If I run this in version: 3.0.1, the error message is 
```
Error in predict_race(voter.file = df_2000, census.geo = "tract", year = "2010",  : 
  unused argument (surname.year = "2000")
```
I believe it means the passed argument: `surname.year` is not supported by the function. Just in case you mean the version, the previously-workable version is 1.0.1.

**Comment by 1beb** [comment]
https://github.com/kosukeimai/wru/releases/tag/0.1-12 You're going to have to use a much older release to get the right data.

**Comment by liaoaoyuan97** [comment]
Got U. It is working now. Thanks!
