### ISSUE TITLE
Incorporate Census 2000 Geo

### ISSUE THREAD

**Issue by liaoaoyuan97** [kosukeimai/wru#149]
Hi, I am wondering if you have a plan to incorporate Census 2000 Geographic data to allow  "2000" as an option in the parameter for https://github.com/kosukeimai/wru/blob/a53fce3c54bcabb0f45e155bc320e18585cd9b91/R/predict_race.R#L152.

Thanks to wru, we can work on our data with missing race of subjects. But our data is back to 2000 and we'd like the imputed race to be as accurate as possible, especially wanting it to comply with the demographic pattern. Would it be possible to priotize it in your development?

Thank you so much!

**Comment by 1beb** [comment]
We do not have plans to go this far back. What you might be able to do is, given lat and long, you might be able to place the person is a 2010 or 2020 geography (like county, block or tract). Then run it using the 2010 data. Closing this one for now as there is no plan to go back that far.

**Comment by liaoaoyuan97** [comment]
All right. Thank you so much!
