### ISSUE TITLE
Census options are not giving correct level of geography

### ISSUE THREAD

**Issue by sonoshah** [kosukeimai/wru#15]
When running the race.pred() it looks like the level of geography is off. Choosing census = "county' results in state estimates, census = "tract" shows county estimates, and census = "block" shows tract estimates.

## Census = "county" 
` race.pred(voters = voters, races = c("white", "black", "latino", 'asian'),census = 'county', census.key= censuskey, demo = FALSE, surname.only=FALSE)`

**Shows the **state** status messages**

`[1] "State  NJ"

[1] "State  NY"

[1] "State  DC"`

## Census = "tract" 
`race.pred(voters = voters, races = c("white", "black", "latino", 'asian'),census = 'tract', census.key= censuskey, demo = FALSE, surname.only=FALSE)`
**Shows the **county** status messages**
`[1] "State  NJ"

[1] "County 1 of 21: 001"

[1] "County 2 of 21: 003"

[1] "County 3 of 21: 005"

[1] "County 4 of 21: 007"

[1] "County 5 of 21: 009"`

## Census = "block" 
`race.pred(voters = voters, races = c("white", "black", "latino", 'asian'),census = 'block', census.key= censuskey, demo = FALSE, surname.only=FALSE)`

**Shows the **tract** status:**

`[1] "State  NJ"

[1] "County 1 of 21: 001"

[1] "for=tract:*&in=state:34+county:001"

[1] "Tract 1 of 70: 000100"

[1] "Tract 2 of 70: 000200"

[1] "Tract 3 of 70: 000300"

[1] "Tract 4 of 70: 000400"

[1] "Tract 5 of 70: 000500"`

and so on. 

I'm not sure what the issue is. This is using the `Voters` dataset included in the `WRU` package, I've also had the same problem with using test data. 

Is this something going on in `census.helper.api` ?

**Comment by kkprinceton** [comment]
The function is working as intended, but the print messages may be a bit misleading. For instance, in your county-level example, the function prints "State NJ" to indicate that all the counties in NJ have been completed. The probabilities you end up with correspond to the county-level race data.

**Comment by kosukeimai** [comment]
@kkprinceton Why don't we modify the print messages so that it's less confusing?

**Comment by sonoshah** [comment]
Ah! I see. Thanks for the clarification!

**Comment by kkprinceton** [comment]
@kosukeimai Sure, I'll do that in my next commit.
