### ISSUE TITLE
improper row sums on geo data

### ISSUE THREAD

**Issue by ericmanning** [kosukeimai/wru#153]
line 185 in `R/census_helper_v2.R` reads:

```geoPopulations <- rowSums(census[,names(census) %in% vars_])```

The current version omits all Asian and Other vars in the geo population total computation (because the Asian and Other variable name vectors in `vars_` have length > 1). Pr(R|G) calculations are incorrect as a result, and worse in places that have high proportions of Asian and Other individuals.

It should read:

``` geoPopulations <- rowSums(census[,names(census) %in% unlist(vars_)])```

**Comment by 1beb** [comment]
Thank you for reporting, we will take a look.

**Comment by 1beb** [comment]
Closed by #154
