### ISSUE TITLE
suffixes

### ISSUE THREAD

**Issue by kosukeimai** [kosukeimai/wru#17]
Create an option of removing suffixes from names in `name.clearn()`  The default should be `TRUE`

**Comment by kkprinceton** [comment]
I have replaced the old name.clean() function with the new census.surname(), which includes the new functionalities that we discussed. This new function includes an option called 'name.clean' (default is TRUE), which performs the following steps to maximize the number of names matched:
- Remove any punctuation from names and search again
- Remove any spaces from names and search again
- Remove suffixes (e.g., Jr) from names and search again
- Split double-barreled surnames into two parts and search first part of name
- Split double-barreled surnames into two parts and search second part of name

The new census.surname() function also has an option called 'impute.missing' (default is TRUE), which imputes race/ethnicity probabilities for all names that could not be matched.
