### ISSUE TITLE
Different Results

### ISSUE THREAD

**Issue by standarddev** [kosukeimai/wru#19]
Hello,

Thank you for updating the code. I noticed that the race prediction function has changed from race.predict to predict_race. Is the name (and the face that it will allow for younger people) the only change?

When I ran the race.predict code last week and rerun it this morning using predict_race, I got different results.

For example, last week I ran 
race.pred(dta, name.clean = TRUE, surname.only = TRUE)
and received this output for the last name ADAME

surname	pred.whi	pred.bla	pred.his	pred.asi	pred.oth
ADAME	0.0661	 0.0064	0.9168	0.0034	0.0073

and this morning I ran
surname <- predict_race(dta, surname.only = TRUE)
and received this output for the last name ADAME. 

surname	pred.whi	pred.bla	pred.his	pred.asi	pred.oth
ADAME	0.0603	0.0046	0.9261	0.0042	0.0048

It is like this across the records I ran both times (~7,000 records). Why is there a difference? I wouldn't expect the calculation to change.

**Comment by kosukeimai** [comment]
We now have the 2010 census name list, which is default.  Your previous calculation may have been based on the 2000 census name list (there is an option to use it as well and so you can try).
