### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by standarddev** [kosukeimai/wru#21]
Hello again,

I am trying to find the program and am getting this error

ablock <- predict_race(dta, census.surname = TRUE, surname.only = FALSE, surname.year = 2010, census.geo = "block",census.key=key, age=TRUE)

Error: cannot allocate vector of size 3.2 Mb

Is that a space issue on my side or is that a space issue for R? Should I lower the number of records I run at one time? When I ran the same code for county and track, I got results fine.

Thanks for your input!

Robin

**Comment by kosukeimai** [comment]
That's a memory problem on your side: I suspect that you are using Windows machine since Linux and MacOSX do not have this problem.  Try this: http://stackoverflow.com/questions/1395229/increasing-or-decreasing-the-memory-available-to-r-processes
