### ISSUE TITLE
merge_surnames fails when no names inferred

### ISSUE THREAD

**Issue by dodger487** [kosukeimai/wru#26]
When predicting race using a dataframe where no names need to be inferred, `merge_surnames` and consequently `predict_race` fails with the error 
```
Error in $<-.data.frame(*tmp*, "surname.match", value = "") :  
  replacement has 1 row, data has 0
```

Here's example code reproducing the issue:
```
library(wru)

# Completes normally
test_inferred <- data.frame(surname = c("Smith", "NOT_A_REAL_LAST_NAME"), 
                            state = c("NY", "NY"))
merge_surnames(test_inferred)

# Produces the error:
# Error in `$<-.data.frame`(`*tmp*`, "surname.match", value = "") : 
#   replacement has 1 row, data has 0
test_not_inferred <- data.frame(surname = c("Smith", "Williams"),
                                state = c("NY", "NY"))
merge_surnames(test_not_inferred)

# This also errors out with the same error:
merge_surnames(test_not_inferred, clean.surname = F)
```

I'm fairly sure this is due to this line of code, as `df2` is empty:
https://github.com/kosukeimai/wru/blob/master/R/merge_surnames.R#L124

However, this also seems to fail when `clean.surname = F` so there could be an error elsewhere as well.

**Comment by kkprinceton** [comment]
Thank you for pointing this out. I found the line of code causing the error and will fix it shortly.

**Comment by kkprinceton** [comment]
I just revised merge_surnames.R. Would you please try it out? @HJ08003

**Comment by dodger487** [comment]
Thank you! Pulling your code down locally it works for me, though updating via CRAN did not. I'm assuming this is not up on CRAN yet? Should I close now, or should I wait until it's up on CRAN?

**Comment by kosukeimai** [comment]
We will upload it to CRAN.  Thanks!
