### ISSUE TITLE
Missing/renamed data in documentation

### ISSUE THREAD

**Issue by potterzot** [kosukeimai/wru#29]
I'm working on a project hoping to use fuzzy string matching to determine ethnicity and came across your work. Seems great and we might try to use your method/data in our matching. Along the way I notcied two potential issues:

* [names.all](https://github.com/kosukeimai/wru/blob/master/man/names.all.Rd) is documented but no longer in the package.

* [surnames2010.Rdata](https://github.com/kosukeimai/wru/blob/master/data/surnames2010.RData) is not documented.

**Comment by kosukeimai** [comment]
@potterzot Thanks for this.  We will remove `names.all.Rd` and we will add a documentation for `surnames2010.Rdata`

**Comment by kkprinceton** [comment]
Just removed extraneous documentation and renamed documentation for surnames2010.RData.
