### ISSUE TITLE
Census API sf1 2010 format changes

### ISSUE THREAD

**Issue by tylerreny** [kosukeimai/wru#31]
It looks like the US census API changed both its endpoint and variable names:

https://www.census.gov/data/developers/updates/api-format-changes--sf1-2010.html

I was trying to figure out how the old variables map to the new ones, but they have no mapping, so I don't know how to adjust my API URL. Thought I'd highlight this so it can be updated in the main functions. Thanks.

**Comment by kkprinceton** [comment]
Thanks for the heads up, and apologies for the delay in replying. I'm looking into this now. In the mean time, you're welcome to email me with your specific issue or code, as I might be able to help.

**Comment by kkprinceton** [comment]
Hi @tylerreny. I just pushed some updates. Would love to know if this now works for your application.

**Comment by ZackBouz** [comment]
@kkprinceton 
**Worked**:
predict_race**(voter.file = voters, census.geo = "county", census.key = "...", party = "PID")
**Did not work:**
county.ca <- census_geo_api(key = "...", state = "CA", geo = "county", age = TRUE, sex = FALSE)
AND
census.ca <- get_census_data(key = "...", state = c("CA"), age = TRUE, sex = FALSE, census.geo = "tract")

**Comment by kkprinceton** [comment]
I suspect the non-working examples are due to a change in how the Census API handles states with a single-digit FIPS code, such as California. Would you please try again?

**Comment by ZackBouz** [comment]
Got a couple server errors while downloading CA census data. Eventually the examples above worked. Awesome
