### ISSUE TITLE
Option to disable imputation in predict_race()

### ISSUE THREAD

**Issue by trang1618** [kosukeimai/wru#33]
Currently, the `merge_surnames` function has the argument `impute.missing` (default is TRUE). However, this argument is not available in `predict_race` which calls `merge_surnames`:

https://github.com/kosukeimai/wru/blob/f6d5ea143e3497948f10a05725a2a5e175c32e65/R/predict_race.R#L98-L100

Would it be possible to add `impute.missing` as an argument to `predict_race`? Similarly for `clean.surname`?

**Comment by solivella** [comment]
Thank you! There is now an `inpute.missing` argument in `predict_race()`. This will be incorporated in the next CRAN release.
