### ISSUE TITLE
Is there a way to flag imputed probablities?

### ISSUE THREAD

**Issue by scarlett** [kosukeimai/wru#39]
Hello! Some of my data received the following warning because they could not be matched to the census list. I'm just wondering if there's a way to flag those observations. I read through the manual and didn't find an option. 

"Probabilities were imputed for 356572 surnames that could not be matched to Census list."

Thank you!
Scarlett

**Comment by 1beb** [comment]
You could likely achieve this as a post-processing step with something like: 

```
preds <- predict_race(...)
preds$imputed <- !preds$surname %in% names.data$surname
```
