### ISSUE TITLE
Age and false positive/negative rate

### ISSUE THREAD

**Issue by soodoku** [kosukeimai/wru#4]
Does the age matter? Why or why not? And if it does, how do I specify it? Can it appears race.pred doesn't give me false negative/positive rate. Do we have some idea of that?

**Comment by kkprinceton** [comment]
You can include age by setting demo = TRUE in the race.pred function, but empirically, we find that it does not substantially improve predictions. You can calculate the false negative and false positive rates if you observe race in your data, but we do not assume users have observed race.

**Comment by soodoku** [comment]
Thanks!

Re. age/year of birth: Got it! Thanks.  
I suppose the concern that I wanted to get at was if I had say data from 1960, rather than say 2010, would I make different inferences about the race of the name? And that is a diff. question than my initial point. And then perhaps one suggestion would be to note that the data are from X year, and may not necessarily work if you want to infer race of 'Charlie Brown' in MS in 1960.   

Re. false -ve/+ve, one proposal would be to simply report the mean false +ve/-ve rate, across all names that you find in your data (or whatever more granular version your model supports). If it is a constant number, then it may be useful to add that to the readme or some other prominent place that provides people a better sense of model's success.
