### ISSUE TITLE
2020 Census data?

### ISSUE THREAD

**Issue by bfschaffner** [kosukeimai/wru#40]
Will this package be updated to work with the 2020 Census data (and Census geographies)?

**Comment by etrrosenman** [comment]
Hi Brian,

Thanks for reaching out! Yes, we do plan to update the package to work with the 2020 census data. The official census release is scheduled for September 30th, and as we understand it, the Census API will be updated to provide the most recent data on or after that date. Our aim is to release an updated version of the software which can access and work with the 2020 data shortly thereafter. 
We are also working on new functionality to incorporate additional name data in estimating ethnicity probabilities, and that functionally may be released alongside the 2020 update. 

Best,

Evan Rosenman

**Comment by ryanmaciej** [comment]
Hello, is there any potential update to getting 2020 census data incorporated into this package?
Thanks,
Ryan

**Comment by etrrosenman** [comment]
Hi Ryan,

We recently incorporated beta code for the 2020 census data into the hwru branch for this package. The code isn't yet fully validated, but the branch is public, so you are welcome to download it and give it a try!

Evan
