### ISSUE TITLE
hexagon logo

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [kosukeimai/wru#46]
Hello wru,

I designed a logo for your package since you didn't have one.

The hexagon has limited space for text so the geolocation had to be ignored unless you want a location icon in the design.

 If you like it or want modifications, let me know. Zane Dax `@StarTrek_Lt`

![hex wru](https://user-images.githubusercontent.com/55933131/144678429-12b9dac3-53b5-41f5-a5b3-32c05631b32a.png)

**Comment by kosukeimai** [comment]
Hey @PythonCoderUnicorn This looks great!

**Comment by kkprinceton** [comment]
Agreed! Nice job

**Comment by kosukeimai** [comment]
Thanks again for this. @PythonCoderUnicorn I added it to the front page.
