### ISSUE TITLE
Please add a CENSUS_API_KEY to github secrets.

### ISSUE THREAD

**Issue by 1beb** [kosukeimai/wru#52]
So that we can include it in CI as env: CENSUS_API_KEY when running tests for e2e

**Comment by kosukeimai** [comment]
@1beb Done.  Let me know if it doesn't work for some reason.

**Comment by 1beb** [comment]
Can you verify that the name of the key is exactly CENSUS_API_KEY and not some other variation? 
![image](https://user-images.githubusercontent.com/421859/167261879-2e59808f-e03c-4edf-a80d-7f2955a62521.png)
It doesn't show us as expected in CI (***)

**Comment by kosukeimai** [comment]
@1beb Now I'm confused.  We want each user to obtain their own Census API key I think.

**Comment by 1beb** [comment]
You are correct. Each user should have their own key. However, for continuous integration we want our real tests to run everytime someone pushes code. That requires a CENSUS_API_KEY. It should see reasonably infrequent use so using your own should be fine. This needs to be added as a secret to github.

**Comment by kosukeimai** [comment]
oh okay. if it's just for testing purposes, then it's fine.  try it now.
