### ISSUE TITLE
Tiny bug in demo command on front page

### ISSUE THREAD

**Issue by sfirke** [kosukeimai/wru#6]
It says `race.pred(voters = data.frame(surname="Smith"), races = c("white", "black", "latino"), census = "tract", census.key "---", demo = TRUE, surname.only=TRUE)`.  There should be an equals sign after `census.key`, so it looks like:

`race.pred(voters = data.frame(surname="Smith"), races = c("white", "black", "latino"), census = "tract", census.key = "---", demo = TRUE, surname.only=TRUE)`.

This caught me off guard when I copy-pasted this and replaced it with my census key.

**Comment by kosukeimai** [comment]
Thanks. Fixed.
