### ISSUE TITLE
Video is private?

### ISSUE THREAD

**Issue by pdwaggoner** [kosukeimai/wru#61]
Hi - Thanks for the great package! The video appears to link to a private source... increasing my curiosity

```
A related song
Watch [this](https://www.youtube.com/watch?v=r5kmCgVhADY)!
```

**Comment by 1beb** [comment]
I think it was `Who Are You by The Who (1978)`. The reference was removed in the incoming version of the package but I'm sure someone will find a public version to put back for posterity.

**Comment by kosukeimai** [comment]
Yes!  https://www.youtube.com/watch?v=LYb_nqU_43w

**Comment by 1beb** [comment]
Added :)
