### ISSUE TITLE
Example of supplying a census tract or block

### ISSUE THREAD

**Issue by sfirke** [kosukeimai/wru#7]
I'm using this package and want to supply specific location info about the voters.  I looked up a census tract near me to try it out, like [this one in Washtenaw County, MI](http://www.usboundary.com/Areas/467011).  Its name is Census Tract 4035, but I see there are other Tract 4035s in other states, and indeed supply this as the tract info to `race.pred` doesn't change the results:

```
> race.pred(voters = data.frame(surname = c("Smith"), tract = 4035), census.key = "MYKEY", surname.only=TRUE)
  surname tract pred.whi pred.bla pred.his pred.asi pred.oth
1   Smith  4035   0.7335   0.2222   0.0156    0.004   0.0247
> race.pred(voters = data.frame(surname = c("Smith")), census.key = "MYKEY", surname.only=TRUE)
  surname pred.whi pred.bla pred.his pred.asi pred.oth
1   Smith   0.7335   0.2222   0.0156    0.004   0.0247
```

Could you provide an example command of supplying census tract and/or block # from a specific location so that I see how it should be used?  This would be valuable to have on the front page README.

**Comment by sfirke** [comment]
Ah, I now see that there's an object `voters` in the package, for demonstration use.  Helpful for seeing how my data should look.  Maybe note that in the README, in addition to supplying the call with `surname =c(
"Smith")`?

E.g.,

> This package contains a data.frame `voters` with sample data.  Some function calls in the documentation reference this object.

**Comment by kosukeimai** [comment]
Thanks. Added this too.
