### ISSUE TITLE
NAMESPACE error

### ISSUE THREAD

**Issue by ckann10** [kosukeimai/wru#70]
I am using the merge_surnames function independently. There seems to be a recent issue with the roxygen2 generated NAMESPACE file where this function is no longer being exported.

The message I get is:

ERROR : 'merge_surnames' is not an exported object from 'namespace:wru'

**Comment by 1beb** [comment]
The funciton is no longer being exported. However, you can access it by using three colons after the package name. For example:

```
wru:::merge_surnames(...)
```
