### ISSUE TITLE
cannot open connection

### ISSUE THREAD

**Issue by missydata** [kosukeimai/wru#76]
I had been using this wru package until recently when I got a new computer.  I don't know if it has to do with version of R but I ran into several problems. This is one of them.  When I ran the following codes I got the following errors. Why does it try to reach a file that has a wrong file path? My username is "tvscanlon" as shown when I installed the package. It tried to reach "TVSCAN~1"

CODES:
install.packages("wru")
library(wru)
future::plan(future::multisession)
data(voters)
predict_race(voter.file = voters, surname.only = T)

ERRORS:
The downloaded binary packages are in
	C:\Users\tvscanlon\AppData\Local\Temp\RtmpeUroUe\downloaded_packages
> library(wru)
> future::plan(future::multisession)
> data(voters)
> predict_race(voter.file = voters, surname.only = T)
Proceeding with last name predictions...
There was an error retrieving dataCannot access release data for repo "kosukeimai/wru".
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'C:\Users\TVSCAN~1\AppData\Local\Temp\RtmpeUroUe/wru-data-first_c.rds', probable reason 'No such file or directory'

**Comment by 1beb** [comment]
Can you `install.packages('piggyback')` and try again. The most recent version of `wru` relies on a newer version of the `piggyback` pacakge.

**Comment by missydata** [comment]
It still showed the same errors after I installed "piggyback" and restarted R.

**Comment by missydata** [comment]
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] wru_1.0.0       piggyback_0.1.4

loaded via a namespace (and not attached):
 [1] statmod_1.4.36    zoo_1.8-10        tidyselect_1.1.2  purrr_0.3.4      
 [5] listenv_0.8.0     lattice_0.20-45   pglm_0.2-3        vctrs_0.4.1      
 [9] generics_0.1.3    usethis_2.1.6     utf8_1.2.2        rlang_1.0.3      
[13] pillar_1.7.0      glue_1.6.2        DBI_1.1.3         plm_2.6-1        
[17] lifecycle_1.0.1   stringr_1.4.0     bdsmatrix_1.3-6   future_1.26.1    
[21] codetools_0.2-18  memoise_2.0.1     miscTools_0.6-26  fastmap_1.1.0    
[25] lmtest_0.9-40     curl_4.3.2        parallel_4.2.1    fansi_1.0.3      
[29] furrr_0.3.0       Rcpp_1.0.8.3      cachem_1.0.6      jsonlite_1.8.0   
[33] parallelly_1.32.0 fs_1.5.2          maxLik_1.5-2      digest_0.6.29    
[37] stringi_1.7.6     gh_1.3.0          dplyr_1.0.9       collapse_1.8.6   
[41] rbibutils_2.2.8   grid_4.2.1        Rdpack_2.3.1      cli_3.3.0        
[45] tools_4.2.1       sandwich_3.0-2    magrittr_2.0.3    PL94171_1.0.2    
[49] tibble_3.1.7      Formula_1.2-4     crayon_1.5.1      pkgconfig_2.0.3  
[53] MASS_7.3-57       ellipsis_0.3.2    httr_1.4.3        assertthat_0.2.1 
[57] rstudioapi_0.13   gitcreds_0.1.1    R6_2.5.1          globals_0.15.1   
[61] nlme_3.1-157      compiler_4.2.1

**Comment by missydata** [comment]
Does R need to reach data on github to run predict_race() function? 
This error seems to indicate it does:

There was an error retrieving dataCannot access release data for repo "kosukeimai/wru".

**Comment by 1beb** [comment]
Yes, it does. Do you have a github personal access token setup in your `.Rprofile` that is outdated?

**Comment by 1beb** [comment]
When you run predict_race, it automatically downloads the name dictionaries from github, here's what I see when running your code: 

```
> predict_race(voter.file = voters, surname.only = T)
Proceeding with last name predictions...
ℹ Downloading "wru-data-census_last_c.rds"...
  |======================================================================| 100%
ℹ Downloading "wru-data-first_c.rds"...
  |======================================================================| 100%
ℹ Downloading "wru-data-last_c.rds"...
  |======================================================================| 100%
ℹ Downloading "wru-data-mid_c.rds"...
  |======================================================================| 100%
ℹ All local files already up-to-date!
```

It appears that you're unable to do so. It's unclear why. I don't see anything in your sessionInfo() that would suggest a problem. If you updated your version of R recently, that could be the source of the problem as packages are often compiled for a specific version of R. 

Can you invoke a vanilla session of R and try the code again?

**Comment by missydata** [comment]
I created and used a personal github token and it still showed the same errors. 

what version of R are you using?

**Comment by 1beb** [comment]
Can you try `update.packages(checkBuilt = TRUE)` (warning: this may take some time, it will recompile packages that have not been updated between versions of R)

**Comment by missydata** [comment]
I don't think it would work for me because I got a new computer and installed R for the first time with R 4.2.1. So there is not an update.

The funny thing is that I also installed R 4.0.3. When I tried to use R 4.0.3, I could not install 'wru' package. I think the new release requires R 4.1 and newer.

**Comment by 1beb** [comment]
I don't have access to a windows machine to be able to test this, my suspicion is that the error is caused by a mismatch of version + built packages. @kosukeimai @etrrosenman @solivella do any of you run on Windows?

**Comment by missydata** [comment]
It seems that the new version of wru package was the problem. I reinstalled the older version 0.1-11 and it works now. Not sure why the new version works for others but does not work for me. I am ok with the older version until it stops working, then I will figure something out. Thanks 1beb for the quick responses

**Comment by 1beb** [comment]
I tested this with a brand new installation of R and RStudio on Windows. I was able to install the package and run the example as expected. I'm not sure how to debug this without additional information.
