### ISSUE TITLE
Variables needed for census.geo = “county”

### ISSUE THREAD

**Issue by mrhumanzee** [kosukeimai/wru#77]
What variables are required in the _voter.file_ data frame to use the option _census.geo = “county”_? Do you need a _county_ variable that that contains 3-digit FIPS codes and a _state_ variable that contains two letter state abbreviations? I know it is impossible to identify counties at the interstate level using only 3-digit FIPS codes.

**Comment by 1beb** [comment]
Data should be structured similar to what you see in the readme. For something that you can explore, consider reviewing the schema provided in the sample data: 

```
library(wru) 
data(voters)

str(voters)
```

**Comment by mrhumanzee** [comment]
1beb, I only have access to names and USPS Zip codes which I plan to convert into county and state FIPS codes. Is this enough information to perform surname and geography based imputation?

**Comment by 1beb** [comment]
The highest level geography that is offered is _county._ See the description for `census.geo` in `?predict_race`. Zip can be fine, but in some places there are allocation factors with county. I would recommend using geocorr from Missouri Data Center to get allocation factors for your data and assess the allocation factors after joining the reference table to your data. Everything 0/1 you're good. Lots in the middle? It's a problem. 

https://mcdc.missouri.edu/applications/geocorr2022.html

**Comment by mrhumanzee** [comment]
Thank you for your help. HUD USER releases a useful crosswalk between Zip codes and counties that I plan to use (https://www.huduser.gov/portal/datasets/usps_crosswalk.html).  Their crosswalks provide the ratio of residential addresses from a zip code that belong in a particular county.
