### ISSUE TITLE
Format for surnames

### ISSUE THREAD

**Issue by mrhumanzee** [kosukeimai/wru#78]
Forgive me if someone else has already asked this question (I was not able to find any documentation on this matter). Is there a particular format that strings in the _surname_ variable have to be in for _predict_race()_ to work? E.g. does name capitalization matter? Do special characters matter or should they be removed? Can surnames be hyphenated? Can surnames be more than one word (i.e. double-barreled names)? Do name suffixes matter or should they be removed?

**Comment by 1beb** [comment]
Hi @mrhumanzee You can download the surname file used by the package directly and inspect it: 

```
piggyback::pb_download("wru-data-census_last_c.rds", repo = "kosukeimai/wru")
r <- readRDS("wru-data-census_last_c.rds")
r$last_name
```
They are all capitalized without any punctuation nor spacing. @solivella or @kosukeimai may know more about how the file was normalized (or it might be in the paper somewhere).
