### ISSUE TITLE
'surname.year' argument doesn't appear to work

### ISSUE THREAD

**Issue by mrhumanzee** [kosukeimai/wru#79]
The _surname.year_ argument does not change the predicted race probabilities when I passed it different values (2000, 2010, and 2020) using the data frame _voters_. The following data frames were all identical:

_df2000 = predict_race(voter.file = voters, surname.only = T,
                 surname.year = 2000)
df2010 = predict_race(voter.file = voters, surname.only = T,
                 surname.year = 2010)
df2020 = predict_race(voter.file = voters, surname.only = T,
                    surname.year = 2020)_

In addition, I was not able to replicate the the probabilities of the command _predict_race(voter.file = voters, surname.only = T)_ as they are shown on the home page of _wru_. E.g., Khanna was predicted as being White with a probability of 0.0049265455 instead of 0.0676000 when I ran the command.

**Comment by 1beb** [comment]
It's because the package no longer has 2000 and 2010 data. I'm not sure how to approach this other than to suggest you use either the old version of the package for 2010 and prior OR by downloading the dictionaries themselves from previous versions of the package and supplying the data to the `name.dictionaries` argument of the `predict_race` function. 

The data are available in the `data/` directory: 

https://github.com/kosukeimai/wru/releases/download/0.1-12/wru_0.1-12.tar.gz

**Comment by robincrlee** [comment]
@mrhumanzee I have a similar question. 
It seems that the surname.year argument is a legacy argument. 

We can look to this page https://github.com/kosukeimai/wru/blob/3a962f1f9ec3ca77168235eafa4c5bcf6a0f4186/R/race_prediction_funs.R

In `race_prediction_funs`, an internal function that the package devs use, we can see in lines 3 to 10 that there are two functions `.predict_race_old` and `.predict_race_new`. Only the old function uses the argument `surname.year`. The new function uses a different dictionary, and doesn't seem to have multiple 

So I think we should expect the argument not affecting the result. 


Also, there doesn't seem to be a separate surnames2020 in the data directory. 
https://github.com/kosukeimai/wru/tree/3a962f1f9ec3ca77168235eafa4c5bcf6a0f4186/data

**Comment by mrhumanzee** [comment]
> It's because the package no longer has 2000 and 2010 data. I'm not sure how to approach this other than to suggest you use either the old version of the package for 2010 and prior OR by downloading the dictionaries themselves from previous versions of the package and supplying the data to the `name.dictionaries` argument of the `predict_race` function.
> 
> The data are available in the `data/` directory:
> 
> https://github.com/kosukeimai/wru/releases/download/0.1-12/wru_0.1-12.tar.gz

I have no problem using the 2020 Census data. Thanks for the insight.
