### ISSUE TITLE
Ideas to debug with surname.only = T

### ISSUE THREAD

**Issue by robincrlee** [kosukeimai/wru#83]
I have a dataframe with addresses and name. The predict_race ran fine when surname.only = F. 
However, when I swapped the argument to surname.only = F, there's an error. It seems related to the data processing step in [merge_name](
https://github.com/kosukeimai/wru/blob/ac20b26490ecc51aaa0779c3f169eb4b2970024d/R/merge_names.R#L168) function. 
I suspect that's the case because that's where I can find `paste(nameType, "name.match' ` code snippet. I believe it's related to unmatched name because in the first result, 33 last name were not matched, and in the error message, there's a message about data has 33 rows. 

But I'm not entirely sure how to debug. Would I need to identify the unmatched names and remove them before processing?
Is there a way for me to call what the `lastNameDict` out?

sample_ct_result <- predict_race(voter.file = sample_ct_data_aug, surname.only = F, census.geo = "tract", census.key = key, 
                                  names.to.use = "surname")

```
Proceeding with last name predictions...
ℹ All local files already up-to-date!
Proceeding with Census geographic data at tract level...
Using Census geographic data from provided census.data object...
State 1 of 1: CT
ℹ All local files already up-to-date!
33 (16.8%) individuals' last names were not matched.
```

sample_ct_result_4 <- predict_race(voter.file = sample_ct_data_aug, surname.only = T)        
```
Proceeding with last name predictions...
ℹ All local files already up-to-date!
ℹ All local files already up-to-date!
Error in `[<-.data.frame`(`*tmp*`, , paste(nameType, "name.match", sep = ""),  : 
  replacement has 2 rows, data has 33
```

**Comment by 1beb** [comment]
Hi @robincrlee can you send me a copy of your sample_ct_data_aug (it looks like it's only 200 rows?) in an RDS file? You can send to brandon at bertelsen dot ca.

**Comment by robincrlee** [comment]
Hi @1beb , I realized where the problem came from while preparing the file for you. 
I have an object with classes as "sf" and "data.frame". It has a column with GIS vector format. Once I forced it as data.frame and dropped the vector column. The problem went away. :)

**Comment by 1beb** [comment]
Ah yes, those sf/boundary files are always a little weird when getting converted to data.frame.
