### ISSUE TITLE
Server with No Internet Error? 

### ISSUE THREAD

**Issue by lydiakayh** [kosukeimai/wru#92]
First, thank you so much for the package! I have been working intermittently on a project and have started again over the holidays. I was able to successfully use the predict_race function in July of this year but now using the same code (although there is a small chance it could have been changed on accident by one of my peers), I am getting an error. Both the sample_race_data and census_race_data referenced in my code are in the global environment. 

Code: 
sample_race_data_wru <- predict_race(voter.file = sample_race_data, census.geo  = "tract", census.data = census_race_data) 

Error: 
<img width="754" alt="Screen Shot 2022-12-29 at 9 08 56 PM" src="https://user-images.githubusercontent.com/83380774/210027609-c16b8540-f766-4f6d-a7a8-e67822bc88eb.png">

The 2006 messages are just updates throughout my code to keep track of where the error was happening. I am using a server with no access to the internet for data privacy reasons and am wondering if that is where the issue is happening?

**Comment by 1beb** [comment]
Hi @lydiakayh you can avoid the internet download by loading the rds files in the most recent release https://github.com/kosukeimai/wru/releases/tag/v1.0.1 in your working directory

- [wru-data-census_last_c.rds](https://github.com/kosukeimai/wru/releases/download/v1.0.1/wru-data-census_last_c.rds)
- [wru-data-first_c.rds](https://github.com/kosukeimai/wru/releases/download/v1.0.1/wru-data-first_c.rds)
- [wru-data-last_c.rds](https://github.com/kosukeimai/wru/releases/download/v1.0.1/wru-data-last_c.rds)
- [wru-data-mid_c.rds](https://github.com/kosukeimai/wru/releases/download/v1.0.1/wru-data-mid_c.rds)

If the software package sees them in your working directory, it won't attempt to download them.
