### ISSUE TITLE
Probabilities don't add up to 1 if a first name is missing

### ISSUE THREAD

**Issue by mrhumanzee** [kosukeimai/wru#93]
I believe there is a bug with _predict_race()_ that causes probabilities to not add up to 1 if one of the first names in the data frame is missing from the first name list. You can verify this by running the following code (obviously, you need to use your own census key). The second time _predict_race()_ is called using the data frame _voters2_, meaningless probabilities are returned.

```
library(wru)
data(voters)
voters2=voters
voters2$first[1]="asdfasdf"
predict_race(voter.file = voters, 
             census.geo = "county", names.to.use = "surname, first",
             census.key = mykey,
             impute.missing = FALSE)
predict_race(voter.file = voters2, 
             census.geo = "county", names.to.use = "surname, first",
             census.key = mykey,
             impute.missing = FALSE)
```

I would like to find a work around to this issue. Do you know how I can check if a first name is recognized by _predict_race()_? If I had the list of first names, I could try to use the _%in%_ operator.

**Comment by mrhumanzee** [comment]
Update:
I was able to obtain a list of first names by downloading the file _wru-data-first_c.rds_. I feel confident I can develop a work around to my problem. However, I have another somewhat unrelated question. What is the difference between _wru-data-census_last_c.rds_ and _wru-data-last_c.rds_? The names of these files imply they are both surname lists with racial probabilities.  Do these two files come from different sources or different time periods? What determines which file is used during race imputation?

**Comment by 1beb** [comment]
Hi @mrhumanzee 

The census labeled one is from census data. The other one was provided by L2, a voterfile provider. This is identified in their paper, on page 2. 

![image](https://user-images.githubusercontent.com/421859/211640770-9edab824-3311-428f-83ed-bd73ffbaa5fe.png)

**Comment by mrhumanzee** [comment]
> Hi @mrhumanzee
> 
> The census labeled one is from census data. The other one was provided by L2, a voterfile provider. This is identified in their paper, on page 2.

Thanks for the response. I notice there is heavy overlap in the surnames contained in the L2 list and the Census list, yet the probabilities for a given name (e.g. the probabilities for the name "Smith") slightly different differ between lists. By default, which probabilities are used when _predict_race()_ is called? Alternatively, is L2 used as a backup if a name cannot be found in the Census list?

**Comment by mrhumanzee** [comment]
For some reason, the command
```
predict_race(voter.file = voters2, 
             census.geo = "county", names.to.use = "surname, first",
             census.key = mykey,
             impute.missing = FALSE)
```
was displayed using scientific notation while the command 
```
predict_race(voter.file = voters, 
             census.geo = "county", names.to.use = "surname, first",
             census.key = mykey,
             impute.missing = FALSE)
```
was not. This made it appear like the probabilities were different from another even though they were the same.
