### ISSUE TITLE
Location of seed attribute after running fBISG

### ISSUE THREAD

**Issue by mrhumanzee** [kosukeimai/wru#95]
When I run the command:

```
df1= predict_race(voter.file = voters, census.geo = "county",
             census.key = yourkey,
             impute.missing = F, names.to.use="surname, first", model="fBISG")
```

I obtain the warning message "fBISG relies on MCMC; for reproducibility, I am setting RNG seed and returning it as attribute 'RNGseed'. To silence this message, you can set a seed explicitly by defining the 'seed' element in the control list." However, _attributes(df1)_ does not reveal any 'RNGseed' attribute. Is this a bug, or am I looking for the attribute in the wrong object?

As a side question, what is the syntax for specifying a seed in _predict_race()_? Is it _predict_race(..., control=list(seed=...))_?

**Comment by kosukeimai** [comment]
@solivella Should we merge this fix?

**Comment by solivella** [comment]
Done! @mrhumanzee please let us know if this does not resolve your issue. Thank you!
