### ISSUE TITLE
Server with no Internet Error #2

### ISSUE THREAD

**Issue by lydiakayh** [kosukeimai/wru#97]
Hello again!

I had previously asked for help with an issue related to being on a server with no internet. It is issue #92.

I am running into another error, which is attached, even after using the options command and putting the files into my working directory. I have also tried putting the files in every folder referenced in my code, just to double check it. 

Do you have any idea what might be happening? I believe it might have to do with the NULL response from the options command? 

Thanks again for all of your help!

**Comment by 1beb** [comment]
For this one, I think the problem is your syntax: 

```
options("wru_data_wd" = getwd()) # this sets the option note the `"name" = value` format. 
```

**Comment by 1beb** [comment]
Can you try a couple of variations, I don't remember off hand which it is: 

```
options(wru_data_wd = "actual/path")
```

**Comment by lydiakayh** [comment]
Thanks! I used that type of code from your first suggestion using the same file path as I did in a command above that worked to make sure it wasn't an issue with the wrong file path name or something like that. Then, using the getOption command, it showed the exact same file path but I am still getting the same error when I run predict_race. I also tried a simpler file path in an unrestricted folder but that returned the same error so it's not an issue related to path length or file restriction, which I've had issues with before.

**Comment by lydiakayh** [comment]
Also, if it would be helpful/less time consuming for you to jump on a Zoom with me rather than going back and forth like this, I would be totally down. I don't want to overstep but wanted to offer in case it would mean less work for you!

**Comment by 1beb** [comment]
Actually just reviewing the code and it's a T/F flag. 

```
options("wru_data_wd" = TRUE)
```

I'll update the docs to make that clearer.

**Comment by lydiakayh** [comment]
Great! That error is gone but there is a new error now. 
<img width="726" alt="Screen Shot 2023-04-11 at 1 52 26 PM" src="https://user-images.githubusercontent.com/83380774/231261089-8a74fbcf-a650-461f-9a03-d7c762591e10.png">

**Comment by lydiakayh** [comment]
Okay got past that issue, I'm sorry if this is has an obvious solution but I've looked through the code on GitHub and have not found a fix for this error (i.e., skipping those mismatching tracts). Is there a way to get around this error with some sort of option? 

<img width="388" alt="Screen Shot 2023-04-13 at 1 14 44 PM" src="https://user-images.githubusercontent.com/83380774/231848166-45ea87ef-8faf-4abf-8610-ffc83b6a483a.png">
